Update CI (1)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -93,20 +93,24 @@ jobs:
                       exit 0
                     fi
 
+                    if [ "x$PUBLISH_USER" = "x" -o "x$PUBLISH_PASS" = "x" ]; then
+                      echo "Missing publication credentials"
+                      exit 1
+                    fi
+
+                    # Make sure to export variables before the first call to `sbt`
+                    # so that the variable are defined in the SBT server;
+                    # Otherwise `sbt` will then run a client connected to a server
+                    # where the variables defined meanwhile are not available.
+                    export PUBLISH_REPO_NAME="Sonatype Nexus Repository Manager"
+                    export PUBLISH_REPO_ID="central.sonatype.com"
+                    export PUBLISH_REPO_URL="https://central.sonatype.com/repository/maven-snapshots/"
+
                     V=`sbt 'show version' 2>&1 | sed 's/\x1b\[0[Jm]//g' | grep '[0-9]\+\.[0-9]\+' | tail -1 | sed 's/\[info\]//' | xargs | tr -cd '[:alnum:]._-'`
 
                     if [ `echo "$V" | grep -cE 'SNAPSHOT$'` -ne 1 ]; then
                       echo "Cannot publish release $V"
                       exit 0
-                    fi
-                    
-                    export PUBLISH_REPO_NAME="Sonatype Nexus Repository Manager"
-                    export PUBLISH_REPO_ID="central.sonatype.com"
-                    export PUBLISH_REPO_URL="https://central.sonatype.com/repository/maven-snapshots/"
-                    
-                    if [ "x$PUBLISH_USER" = "x" -o "x$PUBLISH_PASS" = "x" ]; then
-                      echo "Missing publication credentials"
-                      exit 1
                     fi
                     
                     echo "Publishing artifacts"
